---
title: "data manipulation"
output: github_document
---

```{r setup, warning = F}
library(tidyverse)
library(readxl)
```

## Load in the FAS Litters Data

```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor :: clean_names(litters_df)
```

## 'select'

choose some columns and not others

```{r}
select(litters_df, litter_number, pups_survive)
```

Renaming columns

```{r}
select(litters_df, team = group, Litter_number = litter_number)
```

```{r}
rename(litters_df, team = group, Litter_number = litter_number)
```

select helper

```{r}
select(litters_df, starts_with("pups"))
```

```{r}
select(litters_df, litter_number, everything())
```

```{r}
relocate(litters_df, litter_number)
```

## 'filter'

```{r}
filter(litters_df, pups_survive > 4)
```

```{r}
filter(litters_df, pups_survive == 8)
```

```{r}
filter(litters_df, pups_survive != 8)
```

```{r}
filter(litters_df, group == "Con7")
```

```{r}
filter(litters_df, group %in% c("Con7", "Low7"))
```

## 'mutate'

```{r}
mutate(litters_df, group = str_to_lower(group))
```

## 'arrange'

```{r}
arrange(litters_df, pups_survive)
```



